import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Meta Data depuis layout root",
    template: "%s | Next.js Formation",
  },
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "Tailwind CSS", "Optimisation"],
  authors: [{ name: "Formation Udemy" }],
  creator: "Formation Udemy",
  openGraph: {
    type: "website",
    locale: "fr_FR",
    url: "https://example.com",
    siteName: "Next.js Formation",
    title: "Meta Data depuis layout root",
    description: "Generated by create next app",
  },
  twitter: {
    card: "summary_large_image",
    title: "Meta Data depuis layout root",
    description: "Generated by create next app",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased p-20`}
      >
        {children}
      </body>
    </html>
  );
}
