import React from 'react'
import styles from './pricing.module.css'

export const metadata = {
  title: "Meta Data depuis page pricing",
  description: "Generated by create next app",
  openGraph: {
    title : "Mon site",
    description : "Description de mon site",
  }
};

function page() {
  return (
    <div>
        <h1 className={styles.title}>Pricing</h1>
    </div>
  )
}

export default page